In [10]:
from google.colab import drive
drive.mount('/content/drive')



Mounted at /content/drive


In [1]:
import numpy as np


# 넘파이 함수에 인풋 값은 거의 (행,열) 이라고 보면 된다. 행령 함수이다. 즉 계산도 행렬의 원소끼리 계산한다. 꼭 기억 (행, 열)  (열,)

In [3]:
a = np.array([[2,3], [5,2], [3,4]])

In [4]:
a

array([[2, 3],
       [5, 2],
       [3, 4]])

In [5]:
# 0으로 이뤄진 배열을 만든다

np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
# 1로 이뤄진 배열을 만든다.

np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
# 특정 범위에 있는 원소를 자동으로 만든다.

np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a = np.ones((2,3))

b = np.transpose(a)

In [ ]:
# 설문지 데이터 전처리 하기

# 데이터 전처리란 데이터분석을 좋게 하기 위해 미리 가공하는 일을 말한다.

import usecsv

os.chdir(r'C:\Users\user\python')  # quest.csv를 저장한 경로로 이동합니다.

quest = np.array(usecsv.swich(usecsv.switch(usecsv.opencsv('quest.csv')))  # qeust.csv 파일을 열어 숫자 원소를 실수형으로 바꾼 다음 배열 형태로 quest 객체에 저장합니다.
                 
quest > 5 # 5 보다 크면 True, 작거나 같으면 False 입니다.

quest[quest>5] # 인덱싱을 활용해 5보다 큰수 만 가져온다.

quest[quest > 5]  =  5  # 5보다 큰 점수를 만점인 5점으로 바꿉니다.


usecsv.writecsv('resultcsv.csv', list(quest)) # 결과물을 다시 'resultcsv.csv' 라는 이름으로 저장합니다. (저장할 이름, 저장할 파일형태)




In [ ]:
# 넘파이는 숫자를 많이 다루는 전문분야, 연구분야, 대규모 데이터 다룰때


In [ ]:
# 우리가 검토 해야할 사업이 있다고 가정하자, 그 사업의 사업성을 분석하며 넘파이를 제대로 사용하는 방법을 알아보겠습니다.
# 사업성 분석이란 간단히 말해 이 사업을 했을때 이익이나 손해가 어느정도 나올지 따져보는 것입니다.
# 경제적 타당성은 간다히 말해 이 사업이 우리에게 손실 대비 얼마나 많은 이익을 가져다 줄 수 있는지를 나타내는 개념입니다. 이를 분석하는 순현재가치와 내부수익률입니다.
# 순현재가치 할인된 현금 흐름의 값을 모두 더한 값을 말합니다.
# 내부수익률: 순현재가치를 0으로 만드는 할인율을 말합니다.



In [33]:
# 자본의 현재 가치 구하기

discount = 0.05 # 할인율 = 현재가치가 떨어지는 비율
cashflow = 100  # 현금흐름은 100(억원) 입니다.


def presentvalue(n):
    return (cashflow / ((1 + discount) ** n))

In [34]:
for i in range(20):
    print(presentvalue(i))

100.0
95.23809523809524
90.70294784580499
86.3837598531476
82.27024747918819
78.35261664684589
74.62153966366274
71.06813301301213
67.6839362028687
64.46089162177971
61.39132535407592
58.46792890864373
55.68374181775592
53.03213506452945
50.506795299551854
48.101709809096995
45.811152199140004
43.62966876108571
41.5520654867483
39.57339570166504
