In [1]:
import numpy as np


# 넘파이 함수에 인풋 값은 거의 (행,열) 이라고 보면 된다. 행령 함수이다. 즉 계산도 행렬의 원소끼리 계산한다. 꼭 기억 (행, 열)  (열,)

In [3]:
a = np.array([[2,3], [5,2], [3,4]])

In [4]:
a

array([[2, 3],
       [5, 2],
       [3, 4]])

In [5]:
# 0으로 이뤄진 배열을 만든다

np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
# 1로 이뤄진 배열을 만든다.

np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
# 특정 범위에 있는 원소를 자동으로 만든다.

np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a = np.ones((2,3))

b = np.transpose(a)