In [10]:
from google.colab import drive
drive.mount('/content/drive')



Mounted at /content/drive


In [1]:
import numpy as np


# 넘파이 함수에 인풋 값은 거의 (행,열) 이라고 보면 된다. 행령 함수이다. 즉 계산도 행렬의 원소끼리 계산한다. 꼭 기억 (행, 열)  (열,)

In [3]:
a = np.array([[2,3], [5,2], [3,4]])

In [4]:
a

array([[2, 3],
       [5, 2],
       [3, 4]])

In [5]:
# 0으로 이뤄진 배열을 만든다

np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
# 1로 이뤄진 배열을 만든다.

np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
# 특정 범위에 있는 원소를 자동으로 만든다.

np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a = np.ones((2,3))

b = np.transpose(a)

In [ ]:
# 설문지 데이터 전처리 하기

# 데이터 전처리란 데이터분석을 좋게 하기 위해 미리 가공하는 일을 말한다.

import usecsv

os.chdir(r'C:\Users\user\python')  # quest.csv를 저장한 경로로 이동합니다.

quest = np.array(usecsv.swich(usecsv.switch(usecsv.opencsv('quest.csv')))  # qeust.csv 파일을 열어 숫자 원소를 실수형으로 바꾼 다음 배열 형태로 quest 객체에 저장합니다.
                 
quest > 5 # 5 보다 크면 True, 작거나 같으면 False 입니다.

quest[quest>5] # 인덱싱을 활용해 5보다 큰수 만 가져온다.

quest[quest > 5]  =  5  # 5보다 큰 점수를 만점인 5점으로 바꿉니다.


usecsv.writecsv('resultcsv.csv', list(quest)) # 결과물을 다시 'resultcsv.csv' 라는 이름으로 저장합니다. (저장할 이름, 저장할 파일형태)


